debug: true

loginServer:
  serverIp: "*"
  serverPort: 2106

databaseAddress:
  dbIp: ""
  dbUserName: ""
  dbPassword: ""

bridgeConfig:
  blowFishKey: "encryption"
  bridgeServer:
    serverIp: "*"
    serverPort: 3300

  registeredServers:
    - {
      id: "Main"
    }
    - {
      id: "second"
    }

